config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	resources :products do
		resources :comments
	end
  resources :users
	resources :orders, only: [:index, :show, :create, :destroy]
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'
	
	post 'static_pages/thank_you'
	post 'payments/create'

	root 'static_pages#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rubyapp</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
	<link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">OME</a>
			</div>

			<div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li><li><%= link_to 'Home', static_pages_index_path %></li></li>
					<li><%= link_to 'About', static_pages_about_path %></li>
					<li><%= link_to 'Contact', static_pages_contact_path %></li>
					<li><%= link_to 'New Products', products_path %></li>
					<li id="search">
					<%= form_tag("/products", method: "get") do %>
						<%= label_tag(:q, "Search:") %>
						<%= text_field_tag(:q) %>
						<%= submit_tag("Search") %>
					<% end %>
					</li>
				</ul>
				<ul class="nav pull-right">
					<li>
						<% if user_signed_in? %>
							<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
						<% else %>
							<%= link_to('Login', new_user_session_path) %>
						<% end %>
					</li>
				</ul>
			</div><!-- /.navbar-collapse -->
		</div><!-- /.container-fluid -->
	</nav>
	<div class="alert alert-warning" role="alert">
		<% if notice %>
			<p id="notice" class="alert alert-info"><%= notice %></p>
		<% end %>
		<% if alert %>
			<p class="alert alert-info"><%= alert %></p>
		<% end %>
	</div>
<%= yield %>
	<div class="body-wrap">
	</div>
	
	
	<footer class="footer">
		<div class="container">
			<p class="text-muted">&copy; 2016 Andreaw Suppini</p>
		</div>
	</footer>

</body>
</html>